theme: jekyll-theme-minimal
title: Daniel O'Keefe
logo: "/images/photo_cropped.PNG?raw=true"
description: >
  <center>
  <b>Applications of Data Science</b>
  <br>
  <a href="https://www.linkedin.com/in/daniel-o-keefe-149b2b14b/">LinkedIn</a>
  <a> | </a>
  <a href="https://github.com/DanOKeefe">GitHub</a>   
  <a> | </a>
  <a href="https://medium.com/@dantokeefe">Medium</a> 
